export const questions = {
    truths: [
        "Apa makanan favorit yang bisa kamu makan setiap hari seumur hidup?",
        "Siapa selebriti yang pengen banget kamu ajak dating?",
        "Apa hobi aneh yang kamu punya tapi gak banyak orang tau?",
        "Kalau punya uang 1 miliar, apa 3 barang pertama yang kamu beli?",
        "Pernah gak salah kirim chat memalukan? Ceritain detailnya.",
        "Apa film kartun atau anime favoritmu waktu kecil yang masih kamu suka?",
        "Siapa member di server ini yang menurutmu paling asik diajak nongkrong?",
        "Apa lagu guilty pleasure kamu? (Lagu yang malu-maluin tapi enak)",
        "Kalau bisa tukeran hidup sama satu orang di sini selama sehari, mau sama siapa?",
        "Apa kejadian lucu yang baru aja kamu alamin minggu ini?",
        "Sebutin satu barang di kamar kamu yang paling kamu sayang.",
        "Kalau kamu jadi hantu, siapa orang pertama yang bakal kamu jailin?",
        "Pernah gak naksir guru atau dosen sendiri?",
        "Apa hal paling bodoh yang pernah kamu lakuin demi dapet perhatian gebetan?",
        "Kalau disuruh bikin pulau sendiri, apa nama pulaunya dan aturannya apa?",
        "Siapa orang terakhir yang kamu stalk di Instagram?",
        "Apa kebiasaan tidur kamu yang aneh? (Ngiler, ngorok, jalan?)",
        "Kalau hidup kamu dijadiin film, siapa aktor/aktris yang cocok meranin kamu?",
        "Pernah gak ketiduran di tempat umum? Di mana?",
        "Apa hal yang paling bikin kamu ilfeel sama lawan jenis?",
        "Pernah ngompol pas udah gede? Kapan terakhir kali?",
        "Siapa orang di server ini yang diam-diam kamu anggap menarik/cakep?",
        "Apa hal paling memalukan yang pernah kamu lakuin di depan gebetan?",
        "Pernah bohong sakit biar gak sekolah/kerja/kuliah? Alasannya apa?",
        "Siapa mantan yang paling nyesel kamu putusin atau diputusin?",
        "Pernah gak mandi lebih dari 2 hari? Kenapa?",
        "Apa aib terbesar yang orang tua kamu gak tau sampai sekarang?",
        "Pernah stalk sosmed mantan pake akun fake? Ngapain aja?",
        "Siapa orang yang paling pengen kamu block di sosmed tapi gak enak?",
        "Apa kebohongan terparah yang pernah kamu ucapin ke pacar/gebetan?",
        "Pernah ciuman gak? Kalau udah, kapan first kiss kamu?",
        "Siapa member di sini yang menurutmu paling 'red flag'?",
        "Pernah suka sama pacar temen sendiri? Jujur!",
        "Apa fantasi terliar yang pernah terlintas di pikiran kamu?",
        "Kalau kamu harus nikah sama salah satu member di sini, siapa yang kamu pilih?",
        "Pernah kirim pap (foto) yang 'berbahaya' ke orang lain?",
        "Apa hal nakal yang pernah kamu lakuin di sekolah/kampus?",
        "Pernah ketahuan bohong sama orang tua? Masalah apa?",
        "Siapa orang yang paling sering kamu gibahin di belakang?",
        "Apa hal fisik yang paling kamu gak suka dari diri sendiri?",
        "Kapan terakhir kali kamu nangis sendirian dan kenapa?",
        "Apa ketakutan terbesar kamu dalam hidup yang bikin kamu susah tidur?",
        "Apa penyesalan terbesar kamu sejauh ini yang pengen banget kamu ubah?",
        "Siapa orang yang paling berjasa di hidup kamu dan kenapa?",
        "Apa mimpi yang belum kesampaian sampai sekarang dan bikin kamu sedih?",
        "Kalau bisa memutar waktu, momen apa yang pengen banget kamu perbaiki?",
        "Apa hal yang bikin kamu insecure banget sama diri sendiri?",
        "Siapa orang yang paling kamu sayang di dunia ini melebihi diri sendiri?",
        "Apa arti kebahagiaan menurut versi kamu?",
        "Pernah merasa kesepian banget padahal lagi rame? Ceritain.",
        "Apa trauma masa lalu yang masih menghantui kamu sampai sekarang?",
        "Kalau besok adalah hari terakhir kamu hidup, apa yang mau kamu lakuin?",
        "Apa hal yang pengen banget kamu omongin ke orang tua tapi gak berani?",
        "Siapa orang yang pernah kamu sakiti hatinya dan kamu nyesel banget?",
        "Apa sifat toxic dalam diri kamu yang lagi kamu coba ilangin?",
        "Kapan kamu merasa paling bangga sama diri sendiri?",
        "Apa pandangan kamu tentang pernikahan? Takut atau pengen?",
        "Kalau bisa minta maaf sama satu orang di masa lalu, mau minta maaf ke siapa?",
        "Apa hal yang bikin kamu bertahan hidup sampai hari ini?",
        "Ceritain momen terendah dalam hidup kamu dan gimana cara kamu bangkit."
    ],
    dares: [
        "Kirim stiker paling aneh atau cringe yang kamu punya di chat ini.",
        "Ganti nickname jadi 'Beban Keluarga' atau 'Wibu Bau Bawang' selama 1 ronde.",
        "Nyanyi reff lagu 'Balonku Ada Lima' tapi ganti huruf vokalnya jadi 'O'.",
        "Kirim foto wallpaper HP kamu sekarang (lockscreen & homescreen).",
        "Tulis nama kamu pake siku di chat.",
        "Spam emoji � sebanyak 15 kali.",
        "Screenshot history YouTube terakhir kamu dan kirim sini.",
        "Bilang 'Rawr' atau 'Meong' di setiap akhir kalimat selama 3 menit.",
        "Kirim foto selfie dengan gaya muka paling jelek yang bisa kamu buat.",
        "Sebutin 3 hal yang kamu suka dari orang yang milih tantangan ini.",
        "Baca chat terakhir dari grup keluarga kamu dengan nada dramatis (VN).",
        "Gunakan foto profil pilihan member lain selama 10 menit.",
        "Kirim pesan suara (VN) kamu lagi niruin suara ayam berkokok.",
        "Chat orang random di contact list kamu (pilih acak) dan kirim stiker 'Hai'.",
        "Jelasin tutorial cara bernapas dengan sangat serius lewat VN.",
        "Kirim foto jari kaki kamu (kalau berani).",
        "Tulis status 'Aku sayang admin bot ini' di bio Discord kamu selama 1 jam.",
        "Ngomong pake bahasa Inggris yang dicampur-campur (Jaksel style) selama 2 menit.",
        "Kirim foto makanan terakhir yang kamu makan (kalau ada di galeri).",
        "Tirukan suara salah satu member di sini lewat VN.",
        "Chat mantan atau gebetan bilang 'Aku kangen' terus screenshot reaksinya (kalo gak dibales gpp).",
        "Ganti foto profil jadi foto aib masa kecil (minta member lain yang pilih) selama 1 jam.",
        "Telepon random member di server ini dan nyanyi Happy Birthday dengan semangat.",
        "Teriak 'AKU BUTUH KASIH SAYANG' sekencang-kencangnya di VN.",
        "Chat orang tua kamu bilang 'Ma, Pa, aku mau nikah bulan depan'. Kirim buktinya.",
        "Post foto selfie jelek di story WA/IG sekarang dengan caption 'Feeling cute'.",
        "Gombalin salah satu member di sini (pilih acak) pake voice note sampai dia salting.",
        "Makan cabe rawit satu biji atau minum air garem (kirim video/foto).",
        "Push up 20 kali sambil video call (on cam).",
        "Joget TikTok random (tanpa musik) dan kirim videonya ke sini.",
        "Ganti status Discord jadi 'Lagi nyari jodoh, minat PM' selama 1 hari.",
        "Chat teman sejenis kamu bilang 'Bro/Sis, kayaknya aku suka sama kamu'.",
        "Kirim pesan suara desahan (palsu aja) ke grup ini.",
        "Prank call salah satu kontak di HP kamu, pura-pura jadi kurir paket.",
        "Minum satu gelas air putih tanpa napas (kirim video).",
        "Coret-coret muka sendiri pake spidol/lipstik terus selfie.",
        "DM salah satu member (lawan jenis) bilang 'Kamu manis deh hari ini'.",
        "Baca puisi cinta yang lebay banget buat salah satu member di sini.",
        "Ganti nama kontak pacar/gebetan/sahabat jadi 'Majikan Ku' dan screenshot.",
        "Jilat sikut tangan sendiri (kalau bisa) atau hidung sendiri.",
        "Ceritain satu rahasia besar yang belum pernah kamu ceritain ke siapa pun di sini.",
        "Kirim pesan suara (VN) buat diri kamu di masa depan (1 menit), kasih semangat.",
        "Minta maaf ke satu orang yang pernah kamu sakiti (bisa di server ini atau luar) sekarang juga.",
        "Tulis pesan terima kasih yang tulus buat orang tua kamu dan kirim screenshot-nya.",
        "Jujur tentang perasaan kamu ke seseorang di server ini (kalau ada, sebut inisial aja boleh).",
        "Ceritain momen terberat dalam hidup kamu secara singkat.",
        "Sebutin 3 sifat jelek kamu yang pengen kamu ubah dan minta saran ke member lain.",
        "Peluk guling atau boneka yang ada di dekatmu dan bayangin itu orang yang kamu sayang.",
        "Kirim foto masa kecil kamu yang paling berkesan dan ceritain kenangannya.",
        "Doakan satu hal baik buat semua member di server ini lewat VN.",
        "Kirim chat ke sahabat lama yang udah jarang ngobrol, tanya kabar.",
        "Tulis 3 hal yang kamu syukuri hari ini di chat.",
        "Ceritain tentang 'First Love' kamu dan gimana akhirnya.",
        "Sebutin satu lagu yang selalu bikin kamu sedih/inget kenangan masa lalu.",
        "Janji sama diri sendiri di depan kita semua buat berhenti ngelakuin satu kebiasaan buruk.",
        "Kirim foto langit atau pemandangan di luar jendela kamu sekarang.",
        "Ceritain mimpi aneh yang pernah kamu alamin dan kerasa nyata banget.",
        "Sebutin satu quote atau kata-kata mutiara yang jadi pedoman hidup kamu.",
        "Kasih pujian tulus buat 3 member berbeda di grup ini.",
        "Share satu foto yang punya kenangan sedih buat kamu (kalau mau)."
    ]
};

export function getRandomQuestion(type) {
    const getRandom = (arr) => arr[Math.floor(Math.random() * arr.length)];

    if (type === 'truth') return getRandom(questions.truths);
    if (type === 'dare') return getRandom(questions.dares);

    return Math.random() < 0.5 ? getRandom(questions.truths) : getRandom(questions.dares);
}
